# Generated by Django 5.1.6 on 2026-02-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_favorite_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_tracks',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой')], max_length=1),
        ),
    ]
