services:
  web:
    # Используем твой образ из Docker Hub
    image: georgio8/music_project:latest
    ports:
      - "8000:8000"
    mem_limit: 512m
    # Статику оставляем в именованных томах, если нужно,
    # но локальный маппинг (- .:/app) убираем
    restart: unless-stopped
    env_file:
      - .env
    environment:
      USE_DOCKER: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Добавь хост базы данных, чтобы Django знал куда идти
      DB_HOST: postgres
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: music_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    mem_limit: 320m
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: