module.exports = [
  {
    ignores: [
      "node_modules/**",
      "static/vendor/**",
      "staticfiles/**",
      ".venv/**",
    ],
  },
  {
    files: ["static/js/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        navigator: "readonly",
        fetch: "readonly",
        bootstrap: "readonly",
        gsap: "readonly",
        URLSearchParams: "readonly",
        MutationObserver: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        HTMLAudioElement: "readonly",
        Node: "readonly",
        URL: "readonly",
        sessionStorage: "readonly",
        requestAnimationFrame: "readonly",
        getComputedStyle: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        ScrollToPlugin: "readonly",
        DrawSVGPlugin: "readonly",
        SplitText: "readonly",
        Utils: "readonly",
        animateGenreBtn: "readonly",
        showActiveReveal: "readonly",
        hideActiveReveal: "readonly",
        module: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
    },
  },
  {
    files: ["tests/js/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        describe: "readonly",
        it: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        vi: "readonly",
        global: "readonly",
        Utils: "readonly",
        document: "readonly",
        localStorage: "readonly",
        console: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
    },
  },
];
