# Generated by Django 5.1.6 on 2026-02-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_api", "0002_track"),
        ("users", "0003_remove_user_favorite_tracks_alter_user_gender"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Track",
        ),
    ]
