# Generated by Django 5.1.6 on 2026-03-01 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_api", "0005_playlistlikenotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["user", "created_at"], name="music_api_p_user_id_cb5187_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlistlike",
            index=models.Index(
                fields=["playlist"], name="music_api_p_playlis_d80c02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlistlike",
            index=models.Index(fields=["user"], name="music_api_p_user_id_07f2e4_idx"),
        ),
    ]
