# Generated by Django 5.1.6 on 2026-03-02 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_api", "0006_playlist_music_api_p_user_id_cb5187_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaylistComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="playlist_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="comments",
                        to="music_api.playlist",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="playlistcomment",
            index=models.Index(
                fields=["playlist", "created_at"],
                name="music_api_p_playlis_7b2262_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playlistcomment",
            index=models.Index(
                fields=["author", "created_at"], name="music_api_p_author__ea6fdb_idx"
            ),
        ),
    ]
