# Generated by Django 5.1.6 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_api", "0007_playlistcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="replies",
                to="music_api.playlistcomment",
            ),
        ),
        migrations.AddIndex(
            model_name="playlistcomment",
            index=models.Index(
                fields=["parent", "created_at"], name="music_api_p_parent__4d0df0_idx"
            ),
        ),
    ]
