# Generated by Django 5.1.6 on 2026-03-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_api", "0008_playlistcomment_parent"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="playlistcomment",
            new_name="music_api_p_playlis_b840e6_idx",
            old_name="music_api_p_playlis_7b2262_idx",
        ),
        migrations.RenameIndex(
            model_name="playlistcomment",
            new_name="music_api_p_parent__53a842_idx",
            old_name="music_api_p_parent__4d0df0_idx",
        ),
        migrations.RenameIndex(
            model_name="playlistcomment",
            new_name="music_api_p_author__6495c3_idx",
            old_name="music_api_p_author__ea6fdb_idx",
        ),
    ]
